### ISSUE TITLE
KnnQuery replaced by CoreKnnQuery?

### ISSUE THREAD

**Issue by cemremengu** [carlyrichmond/gopher-hunting-elasticsearch#2]
`KnnQuery` type no longer seems to have `K` parameter. Instead there is `CoreKnnQuery` which has that. There is also `KnnSearch`.

Could you please confirm this change?

**Comment by carlyrichmond** [comment]
Thanks for raising @cemremengu! I haven't updated this example in a while so I'll need to dive in and take a look. Happy to keep you posted!

**Comment by cemremengu** [comment]
Thank you! I am trying to get started with Go and Elasticsearch (for a RAG application) and this was the only example I could find. Any examples for creating and adding to an index with a dense vector using the library are also greatly appreciated.

**Comment by carlyrichmond** [comment]
Hi @cemremengu,

I hope you're well. Thanks again for the heads up. I've had a stab at upgrading the code today, and have pushed the updates. I've used `KnnSearch` in place of `KnnQuery`. Hopefully those examples will help you going forward.

Regarding your question about adding a document to an index with a dense vector, I assume you want to index a document within Go? You would specify the embedding as part of your document struct and then use the `Request` method similar to [this example in the documentation](https://www.elastic.co/guide/en/elasticsearch/client/go-api/current/examples.html).

Hope that helps!

**Comment by cemremengu** [comment]
Thanks so much for your help!
